# Generated by Django 2.1.7 on 2019-11-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('question_text', models.CharField(max_length=512)),
                ('question_response', models.CharField(max_length=512)),
                ('sequence_id', models.IntegerField()),
                ('next_sequence_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
